
export const QUEUE_SAVE_INITIATED = 'QUEUE_SAVE_INITIATED';
export const QUEUE_SAVED_SUCCESS = 'QUEUE_SAVED_SUCCESS';
export const QUEUE_SAVED_FAILED = 'QUEUE_SAVED_FAILED';
export const QUEUE_DELETE_INITIATED = 'QUEUE_DELETE_INITIATED';
export const QUEUE_DELETED_SUCCESS = 'QUEUE_DELETED_SUCCESS';
export const QUEUE_DELETED_FAILED = 'QUEUE_DELETED_FAILED';
export const QUEUE_EDIT_INITIATED = 'QUEUE_EDIT_INITIATED';
export const QUEUE_EDITED_SUCCESS = 'QUEUE_EDITED_SUCCESS';
export const QUEUE_EDITED_FAILED = 'QUEUE_EDITED_FAILED';
export const QUEUE_GET_INITIATED = 'QUEUE_GET_INITIATED';
export const QUEUE_GET_CALL_SUCCESS = 'QUEUE_GET_CALL_SUCCESS';
export const QUEUE_GET_CALL_FAILED = 'QUEUE_GET_CALL_FAILED';
export const QUEUE_INPUT_ACTION ='QUEUE_INPUT_ACTION';
export const QUEUE_ROW_EDIT = 'QUEUE_ROW_EDIT';
export const QUEUE_POP_INITIAL = 'QUEUE_POP_INITIAL';

